### ISSUE TITLE
New user, sketchbook dies when first run

### ISSUE THREAD

**Issue by davepoulsen** [gwygonik/SquiggleDraw#17]
Hi -

FIrst time user on MacOS Catalina.  I downloaded the latest Processing 3 today, and the latest ControlP5 library, and installed that all and verified it was working.  I also downloaded SquiggleDraw from this site just today.

When I load it up and run it, I get the following error/traceback:

processing.app.SketchException: Badly formed character constant (expecting quote, got `)
	at processing.mode.java.preproc.PdePreprocessor.checkForUnterminatedMultilineComment(PdePreprocessor.java:831)
	at processing.mode.java.preproc.PdePreprocessor.write(PdePreprocessor.java:868)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:253)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:155)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:122)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:104)
	at processing.mode.java.JavaMode.handleLaunch(JavaMode.java:122)
	at processing.mode.java.JavaEditor.lambda$0(JavaEditor.java:1099)
	at java.lang.Thread.run(Thread.java:748)

The statement in question, indicated in the Processing GUI, is:

  </option></form><form class="js-site-search-form" role="search" aria-label="Site" data-scope-type="Repository" data-scope-id="74513269" data-scoped-search-url="/gwygonik/SquiggleDraw/search" data-owner-scoped-search-url="/users/gwygonik/search" data-unscoped-search-url="/search" action="/gwygonik/SquiggleDraw/search" accept-charset="UTF-8" method="get">

If this is changed from '"` to '"' (in multiple places in the script), the next error is on the DOCTYPE html line objecting to the !  Don't know how to fix this one, or what else is hiding behind it.

**Comment by oskay** [comment]
Can you clarify what it is that you changed, or what statement is indicated in the GUI?

The character <code>`</code> does not appear in [SquiggleDraw.pde](https://github.com/gwygonik/SquiggleDraw/blob/master/SquiggleDraw/SquiggleDraw.pde).

**Comment by davepoulsen** [comment]
Ok, wow, I see that what I downloaded was *very* strange.  I think it must have been operator error on the Github web site (I stupidly didn't just clone the repo).  Got the real file and it works now.  Sorry for the inconvenience!

**Comment by gwygonik** [comment]
Seems like a non-issue here. Closing
